"""add is_active field in trips table

Revision ID: 8cbfa8d0e747
Revises: b748c935c154
Create Date: 2025-12-15 04:34:54.414781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cbfa8d0e747'
down_revision: Union[str, Sequence[str], None] = 'b748c935c154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'is_active')
    # ### end Alembic commands ###
