"""use UUID PKs and typed models

Revision ID: c0da2ffa33d8
Revises: 5891d439ec82
Create Date: 2025-12-07 19:44:32.749005

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0da2ffa33d8"
down_revision: Union[str, Sequence[str], None] = "5891d439ec82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
