"""add trip/participant relationship

Revision ID: f1f2c6756755
Revises: c0da2ffa33d8
Create Date: 2025-12-07 21:21:54.857439

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1f2c6756755"
down_revision: Union[str, Sequence[str], None] = "c0da2ffa33d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("participants", sa.Column("trip_id", sa.UUID(), nullable=False))
    op.create_unique_constraint(
        "uq_participant_trip_name", "participants", ["trip_id", "name"]
    )
    op.create_foreign_key(
        "fk_participants_trip_id_trips_id", "participants", "trips", ["trip_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_participants_trip_id_trips_id", "participants", type_="foreignkey"
    )
    op.drop_constraint("uq_participant_trip_name", "participants", type_="unique")
    op.drop_column("participants", "trip_id")
    # ### end Alembic commands ###
